# The title is the title of your Add-On
title: Page Stats
# The description will be shown above the form when activating the Add-On
description: This will return a csv file containing total pages, average number of pages, and link the largest and small document with their number of pages for a given selection of documents.
# Type should always be object
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the currently selected documents
  - selected
# Properties are the fields for your form
properties: {}
categories:
  - statistical
